package model

import (
	"database/sql"
	"time"

	"github.com/uptrace/bun"
)

// Dashboard is the bun model for the bi_dashboard table (migration 00005).
//
// The row is addressed by a non-guessable UUID string generated by the
// application (uuid.NewV7), never by an auto-increment integer: an enumerable
// id in a system without authentication would let anyone walk the whole table.
//
// LayoutJSON is carried as a plain string even though the column is JSONB —
// the same convention as model.Chart.Config. This batch never interprets the
// layout document: the only code that looks inside it is the chart-reference
// lookup, and that goes through a jsonpath predicate in SQL.
//
// DeletedAt is json:"-" like every other soft-delete column: nothing is ever
// physically deleted.
type Dashboard struct {
	bun.BaseModel `bun:"bi_dashboard"`

	ID          string         `bun:"id,pk" json:"id"`
	Name        string         `bun:"name,notnull" json:"name"`
	Description sql.NullString `bun:"description" json:"description"`
	LayoutJSON  string         `bun:"layout_json,notnull" json:"layout_json"`
	Status      string         `bun:"status,notnull" json:"status"`
	OwnerID     sql.NullInt32  `bun:"owner_id" json:"owner_id"`
	TenantID    sql.NullInt32  `bun:"tenant_id" json:"tenant_id"`
	CreatedAt   time.Time      `bun:"created_at,notnull" json:"created_at"`
	UpdatedAt   time.Time      `bun:"updated_at,notnull" json:"updated_at"`
	DeletedAt   sql.NullTime   `bun:"deleted_at" json:"-"`
}

// TableName satisfies bun's table naming (also covered by the bun tag).
func (*Dashboard) TableName() string { return "bi_dashboard" }
