/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 样例端点，验证统一响应 Envelope 的契约建模。
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 业务状态码，与 backend/internal/response/response.go 常量一一对应。
         * @enum {integer}
         */
        ResponseCode: 20000 | 20100 | 20200 | 20300 | 20400 | 20500 | 50000;
        /** @description 统一响应封装；HTTP 状态码恒为 200，业务状态由 code 表达。 */
        Envelope: {
            code: components["schemas"]["ResponseCode"];
            /** @description 提示消息；成功为 "success"，错误为可读错误描述 */
            msg: string;
            /** @description 请求追踪 ID（X-Request-ID） */
            trace: string;
            /** @description 业务数据；错误或无数据时为空对象 {}，不为 null */
            data: unknown;
        };
        HealthData: {
            /** @example ok */
            status: string;
        };
        /** @description GET /health 响应：Envelope 特化 data 为 HealthData。 */
        HealthResponse: components["schemas"]["Envelope"] & {
            data: components["schemas"]["HealthData"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTTP 恒 200；服务健康由 Envelope.code = 20000 表达 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
