// Package idls provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package idls

// Defines values for OkDataStatus.
const (
	Ok OkDataStatus = "ok"
)

// Valid indicates whether the value is a known member of the OkDataStatus enum.
func (e OkDataStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ResponseCode.
const (
	CodeBadRequest    ResponseCode = 20100
	CodeBusinessError ResponseCode = 20400
	CodeInternalError ResponseCode = 50000
	CodeNotFound      ResponseCode = 20300
	CodeSuccess       ResponseCode = 20000
	CodeThirdPartyErr ResponseCode = 20500
	CodeUnauthorized  ResponseCode = 20200
)

// Valid indicates whether the value is a known member of the ResponseCode enum.
func (e ResponseCode) Valid() bool {
	switch e {
	case CodeBadRequest:
		return true
	case CodeBusinessError:
		return true
	case CodeInternalError:
		return true
	case CodeNotFound:
		return true
	case CodeSuccess:
		return true
	case CodeThirdPartyErr:
		return true
	case CodeUnauthorized:
		return true
	default:
		return false
	}
}

// Chart 图表响应实体（entity.Chart，backend/internal/domain/entity/chart.go）。
// config 是 JSON 文档的字符串形态（后端以 string 存储，非对象）。
type Chart struct {
	// ChartType 后端不做强校验、落库什么返回什么。查询层已知取值：table / bar / line / pie / area / scatter / pivot；未知值按 axis 处理器回退 （query.GetProcessor default 分支）。
	ChartType string `json:"chart_type"`

	// Config 图表配置的 JSON 字符串；创建/更新为空时后端写 "{}"。
	Config string `json:"config"`

	// CreatedAt RFC3339 时间；数据库时间戳无效时为空字符串。
	CreatedAt string `json:"created_at"`
	DatasetId int    `json:"dataset_id"`
	Id        int    `json:"id"`
	Name      string `json:"name"`

	// UpdatedAt RFC3339 时间；数据库时间戳无效时为空字符串。
	UpdatedAt string `json:"updated_at"`
}

// ChartCreateRequest POST /api/charts 请求体。后端整体绑定 entity.Chart（created_at/updated_at 不参与落库映射；id 会被 toChartModel 透传进 insert——传非零值有指定主键风险， 故本 schema 不定义 id）；name/dataset_id/chart_type 为规范性收紧的 required （后端零值可过，见 task-3 报告）。
type ChartCreateRequest struct {
	// ChartType 已知取值见 Chart.chart_type；后端不做枚举校验。
	ChartType string `json:"chart_type"`

	// Config JSON 字符串；缺省/空串后端填 "{}"。
	Config    *string `json:"config,omitempty"`
	DatasetId int     `json:"dataset_id"`
	Name      string  `json:"name"`
}

// ChartDataResponse GET /api/charts/{id}/data 响应：v1 配置时 data 为与 ChartDataResult.data 相同的判别形状（契约上 oneOf 语义，成员为 ChartTableResponse / ChartPieResponse / ChartAxisResponse / ChartScatterResponse / ChartPivotResponse，按图表 chart_type 判别，不投影 select_sql/count_sql）； 旧结构/损坏/空配置回退为裸 DataRow[]。生成物与 ChartDataResult.data 同理 采用无类型 schema（Go interface{} / TS unknown），消费方判别。
type ChartDataResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data v1 配置为查询处理器输出（五形状之一，见上），legacy 回退为 DataRow[]（经归一化恒为数组）。
	Data interface{} `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// ChartDataResult POST /api/charts/query 的业务负载（entity.ChartDataResult，chart.go:39-43）。 data 为查询处理器输出，是按 chart_type 判别的五形状（契约上 oneOf 语义、 未生成 union 类型：data 为无类型 schema，成员见下方各 Chart*Response schema；pie/scatter/table 成员间存在结构重叠，消费方以 chart_type 为准， 不做运行时判别）。data 成功时恒为非 null （response 归一化保证集合字段不为 null）。
type ChartDataResult struct {
	// CountSql 生成的计数 SQL；仅 chart_type=table 且携带 pagination 分支返回 （executor.Execute 的 count 查询路径），其余形状缺省。
	CountSql *string `json:"count_sql,omitempty"`

	// Data 查询处理器输出，形状由 chart_type 判别（oneOf 语义，成员见下方各 schema； 为不引入 oapi-codegen runtime 依赖，Go 生成物为无类型 interface{}， 消费方按 ChartQueryRequest.chart_type 手动判别，五成员为 ChartTableResponse / ChartPieResponse / ChartAxisResponse / ChartScatterResponse / ChartPivotResponse）。
	Data interface{} `json:"data"`

	// SelectSql 生成的取数 SQL（entity omitempty；成功路径恒非空）。
	SelectSql *string `json:"select_sql,omitempty"`
}

// ChartListResponse GET /api/charts 响应：data 为 Chart 数组。
type ChartListResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`
	Data []Chart      `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// ChartMetricConfig 指标聚合配置（entity.MetricConfig，chart.go:26-30）。
type ChartMetricConfig struct {
	// Agg 聚合函数：sum / avg / count / max / min；未知值后端按 SUM 回退 （query.AggregationType.GetAggFunc default）。
	Agg string `json:"agg"`

	// Alias omitempty：结果列别名，缺省时后端用 field 原名（ResolveAlias）。
	Alias *string `json:"alias,omitempty"`
	Field string  `json:"field"`
}

// ChartPagination 图表查询分页（entity.Pagination / query.Pagination，字段一致）。契约统一为 limit/offset，page/page_size 是旧协议遗留：Batch 3 迁移到 limit/offset， 当前实现仍以本对象为准，故字段保留并标记 deprecated。
type ChartPagination struct {
	// Page 页码（从 1 开始）；executor 生成 OFFSET = (page-1)*page_size。
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Page int `json:"page"`

	// PageSize 每页行数；executor 生成 LIMIT。0 会参与除零（total_pages），调用方须给正值。
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	PageSize int `json:"page_size"`
}

// ChartQueryRequest POST /api/charts/query 请求体（entity.ChartQueryRequest，旧协议）。
type ChartQueryRequest struct {
	// ChartType 决定响应 data 形状：table -> ChartTableResponse；pie -> ChartPieResponse； bar/line/area 及未知 -> ChartAxisResponse；scatter -> ChartScatterResponse； pivot -> ChartPivotResponse。
	ChartType string `json:"chart_type"`
	DatasetId int    `json:"dataset_id"`

	// Dims 分组维度列；pie/axis 族取 dims[0] 作类目/X 轴，多余维度作 series 组合。
	Dims *[]string `json:"dims,omitempty"`

	// Filters 过滤条件（entity.Filter）；键为 operator（非 op），含前端未使用的 id 键。
	Filters *[]Filter `json:"filters,omitempty"`

	// Metrics 指标数组；scatter 需至少 2 个指标（第 1 个为 X、第 2 个为 Y），空则 pie/axis 返回空形状。
	Metrics []ChartMetricConfig `json:"metrics"`

	// Pagination 图表查询分页（entity.Pagination / query.Pagination，字段一致）。契约统一为 limit/offset，page/page_size 是旧协议遗留：Batch 3 迁移到 limit/offset， 当前实现仍以本对象为准，故字段保留并标记 deprecated。
	Pagination *ChartPagination `json:"pagination,omitempty"`
	Sort       *SortConfig      `json:"sort,omitempty"`
}

// ChartQueryResponse POST /api/charts/query 响应：data 为 ChartDataResult。
type ChartQueryResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data POST /api/charts/query 的业务负载（entity.ChartDataResult，chart.go:39-43）。 data 为查询处理器输出，是按 chart_type 判别的五形状（契约上 oneOf 语义、 未生成 union 类型：data 为无类型 schema，成员见下方各 Chart*Response schema；pie/scatter/table 成员间存在结构重叠，消费方以 chart_type 为准， 不做运行时判别）。data 成功时恒为非 null （response 归一化保证集合字段不为 null）。
	Data ChartDataResult `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// ChartResponse 图表 CRUD 响应：data 为单个 Chart。
type ChartResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 图表响应实体（entity.Chart，backend/internal/domain/entity/chart.go）。
	// config 是 JSON 文档的字符串形态（后端以 string 存储，非对象）。
	Data Chart `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// ChartUpdateRequest PUT /api/charts/{id} 请求体（handler 匿名 struct：name/dataset_id/ chart_type/config）。全量覆盖语义：未提供的可填字段以零值写库。
type ChartUpdateRequest struct {
	ChartType string `json:"chart_type"`

	// Config 缺省/空串被后端替换为 "{}"（覆盖原配置，非保留）。
	Config    *string `json:"config,omitempty"`
	DatasetId int     `json:"dataset_id"`
	Name      string  `json:"name"`
}

// ColumnInfo 列元数据；datasource handler 以 map 组装，仅含 name/data_type/comment 三个键（前端手写的 role/is_virtual/expression 不由该端点返回）。
type ColumnInfo struct {
	Comment  string `json:"comment"`
	DataType string `json:"data_type"`
	Name     string `json:"name"`
}

// ColumnListResponse GET /api/datasources/{id}/tables/{table}/columns 响应：data 为 ColumnInfo 数组。
type ColumnListResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`
	Data []ColumnInfo `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// DataRow 结果行：列名到任意 JSON 值的映射，值可能为 null。
type DataRow map[string]interface{}

// Dataset 数据集响应实体（entity.Dataset）。tags/columns/quality_rules/shard_keys 是 JSON 文档的字符串形态；指针字段序列化时键恒在，值可为 null。
type Dataset struct {
	AccelerateConfig *string `json:"accelerate_config"`

	// Columns DatasetColumn 数组的 JSON 字符串；缺省 "[]"。
	Columns string `json:"columns"`

	// CreatedAt RFC3339 时间；数据库时间戳无效时为空字符串。
	CreatedAt    string  `json:"created_at"`
	DatasourceId int     `json:"datasource_id"`
	Description  *string `json:"description"`
	Id           int     `json:"id"`

	// Mode 当前后端语义为 "direct"（前端类型含 "accelerated"，后端不产出）。
	Mode        string  `json:"mode"`
	Name        string  `json:"name"`
	PreviewData *string `json:"preview_data"`

	// QualityRules JSON 数组字符串；缺省 "[]"。
	QualityRules string  `json:"quality_rules"`
	QuerySql     *string `json:"query_sql"`

	// QueryType "table" 或 "sql"。
	QueryType       string  `json:"query_type"`
	RefreshStrategy *string `json:"refresh_strategy"`
	ShardEnabled    bool    `json:"shard_enabled"`

	// ShardKeys 分片键的 JSON 数组字符串。
	ShardKeys string  `json:"shard_keys"`
	TableName *string `json:"table_name"`

	// Tags JSON 数组字符串，如 '["a","b"]'；缺省 "[]"。
	Tags string `json:"tags"`

	// UpdatedAt RFC3339 时间；数据库时间戳无效时为空字符串。
	UpdatedAt string `json:"updated_at"`
}

// DatasetColumn 数据集列定义（entity.DatasetColumn）；JSON 字段名为 snake_case 的 type_config。
type DatasetColumn struct {
	Comment string `json:"comment"`
	Expr    string `json:"expr"`
	Name    string `json:"name"`

	// Role "dimension" 或 "metric"。
	Role string `json:"role"`

	// Type 标准数据类型（int/float/decimal/string/date/datetime/array/dict/boolean 等）。
	Type string `json:"type"`

	// TypeConfig 类型相关配置（entity.TypeConfig）。
	TypeConfig TypeConfig `json:"type_config"`
}

// DatasetColumnListResponse GET /api/datasets/{id}/columns 响应：data 为 DatasetColumn 数组。
type DatasetColumnListResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode    `json:"code"`
	Data []DatasetColumn `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// DatasetCreateRequest POST /api/datasets 请求体。table_name/query_sql/description 未传或为空串时 后端置为 null；query_type/mode 为空缺省 "table"/"direct"；tags/columns 为空 缺省 "[]"。
type DatasetCreateRequest struct {
	// Columns DatasetColumn 数组的 JSON 字符串。
	Columns      *string `json:"columns,omitempty"`
	DatasourceId int     `json:"datasource_id"`
	Description  *string `json:"description,omitempty"`

	// Mode 为空时后端缺省 "direct"。
	Mode     *string `json:"mode,omitempty"`
	Name     string  `json:"name"`
	QuerySql *string `json:"query_sql,omitempty"`

	// QueryType "table" 或 "sql"。
	QueryType    string `json:"query_type"`
	ShardEnabled *bool  `json:"shard_enabled,omitempty"`

	// ShardKeys 分片键的 JSON 数组字符串。
	ShardKeys *string `json:"shard_keys,omitempty"`
	TableName *string `json:"table_name,omitempty"`

	// Tags JSON 数组字符串（非数组本体）。
	Tags *string `json:"tags,omitempty"`
}

// DatasetListResponse GET /api/datasets 响应：data 为 Dataset 数组。
type DatasetListResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`
	Data []Dataset    `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// DatasetPreviewResponse GET /api/datasets/{id}/preview 响应：data 为 PreviewResult。
type DatasetPreviewResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 预览结果（entity.PreviewResult）；两字段经 response 归一化， 恒为数组（不会为 null）。
	Data PreviewResult `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// DatasetQueryResponse POST /api/datasets/{id}/query 响应：data 为结果行数组。
type DatasetQueryResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`
	Data []DataRow    `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// DatasetResponse 数据集 CRUD / 列更新响应：data 为单个 Dataset。
type DatasetResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 数据集响应实体（entity.Dataset）。tags/columns/quality_rules/shard_keys 是 JSON 文档的字符串形态；指针字段序列化时键恒在，值可为 null。
	Data Dataset `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// DatasetUpdateRequest PUT /api/datasets/{id} 请求体（id 走路径，不在体内）。与 DatasetCreateRequest 同构，但为取回并保留语义：name/datasource_id/query_type 必填恒覆盖（query_type/mode 为空缺省 "table"/"direct"）；可选字符串元数据 tags/columns/shard_keys 及 table_name/query_sql/description 未传或为空串时 保留库中现值（与 datasource.Update 省略 password 即保留同一约定），显式 "[]" 仍可清空；quality_rules/created_at/updated_at 等体外的列恒保留不被覆盖。
type DatasetUpdateRequest struct {
	// Columns DatasetColumn 数组的 JSON 字符串。
	Columns      *string `json:"columns,omitempty"`
	DatasourceId int     `json:"datasource_id"`
	Description  *string `json:"description,omitempty"`

	// Mode 为空时后端缺省 "direct"。
	Mode     *string `json:"mode,omitempty"`
	Name     string  `json:"name"`
	QuerySql *string `json:"query_sql,omitempty"`

	// QueryType "table" 或 "sql"。
	QueryType    string `json:"query_type"`
	ShardEnabled *bool  `json:"shard_enabled,omitempty"`

	// ShardKeys 分片键的 JSON 数组字符串。
	ShardKeys *string `json:"shard_keys,omitempty"`
	TableName *string `json:"table_name,omitempty"`

	// Tags JSON 数组字符串（非数组本体）。
	Tags *string `json:"tags,omitempty"`
}

// Datasource 数据源响应实体（entity.Datasource）。password 为 json:"-" 永不外泄，
// 因此本 schema 不含 password 字段。
type Datasource struct {
	// CreatedAt RFC3339 时间；数据库时间戳无效时为空字符串。
	CreatedAt    string `json:"created_at"`
	DatabaseName string `json:"database_name"`
	Host         string `json:"host"`
	Id           int    `json:"id"`
	Name         string `json:"name"`
	Port         int    `json:"port"`

	// Type 驱动类型；后端 datasource.NewDriver 支持 postgresql / mysql / clickhouse / starrocks（创建时后端不做枚举强校验，落库什么返回什么）。
	Type string `json:"type"`

	// UpdatedAt RFC3339 时间；数据库时间戳无效时为空字符串。
	UpdatedAt string `json:"updated_at"`
	Username  string `json:"username"`
}

// DatasourceCreateRequest POST /api/datasources 请求体；password 仅出现在请求侧。
type DatasourceCreateRequest struct {
	DatabaseName string `json:"database_name"`
	Host         string `json:"host"`
	Name         string `json:"name"`

	// Password 连接密码；落库前 AES-GCM 加密（DATARAY_SECURITY_KEY）。
	Password *string `json:"password,omitempty"`
	Port     int     `json:"port"`

	// Type 为空时后端缺省填 "postgresql"。
	Type     string `json:"type"`
	Username string `json:"username"`
}

// DatasourceListResponse GET /api/datasources 响应：data 为 Datasource 数组。
type DatasourceListResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`
	Data []Datasource `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// DatasourcePreviewRequest POST /api/datasources/{id}/preview 请求体；table_name 与 query_sql 按 query_type 二选一（"table" 用 table_name 且须为合法标识符，"sql" 用 query_sql）， 后端不做强校验，故均非 required。
type DatasourcePreviewRequest struct {
	QuerySql *string `json:"query_sql,omitempty"`

	// QueryType "table" 或 "sql"；缺省/其他值按 table 分支处理。
	QueryType *string `json:"query_type,omitempty"`
	TableName *string `json:"table_name,omitempty"`
}

// DatasourcePreviewResponse POST /api/datasources/{id}/preview 响应。
type DatasourcePreviewResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 预览结果（entity.PreviewResult）；两字段经 response 归一化， 恒为数组（不会为 null）。
	Data PreviewResult `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// DatasourceResponse 数据源 CRUD 响应：data 为单个 Datasource。
type DatasourceResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 数据源响应实体（entity.Datasource）。password 为 json:"-" 永不外泄，
	// 因此本 schema 不含 password 字段。
	Data Datasource `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// DatasourceTestConnectionRequest POST /api/datasources/test 请求体（无 name，不落库）。
type DatasourceTestConnectionRequest struct {
	DatabaseName string  `json:"database_name"`
	Host         string  `json:"host"`
	Password     *string `json:"password,omitempty"`
	Port         int     `json:"port"`

	// Type 为空时后端缺省填 "postgresql"。
	Type     string `json:"type"`
	Username string `json:"username"`
}

// DatasourceUpdateRequest PUT /api/datasources/{id} 请求体。password 可缺省/空串：
// 后端保留已存密码，不覆盖为空。
type DatasourceUpdateRequest struct {
	DatabaseName string `json:"database_name"`
	Host         string `json:"host"`
	Name         string `json:"name"`

	// Password 空字符串或缺省表示保留原密码。
	Password *string `json:"password,omitempty"`
	Port     int     `json:"port"`
	Type     string  `json:"type"`
	Username string  `json:"username"`
}

// Envelope 统一响应封装；HTTP 状态码恒为 200，业务状态由 code 表达。
type Envelope struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 业务数据；错误或无数据时为空对象 {}，不为 null
	Data interface{} `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// FieldDistribution 字段值分布（entity.FieldDistribution）；distribution 恒为数组。
type FieldDistribution struct {
	Distribution []FieldValueCount `json:"distribution"`
	FieldName    string            `json:"field_name"`
	TotalCount   int64             `json:"total_count"`
	UniqueCount  int               `json:"unique_count"`
}

// FieldDistributionRequest POST /api/datasources/{id}/field-distribution 请求体。
type FieldDistributionRequest struct {
	// FieldName 统计字段名；缺失时后端返回 20100。
	FieldName string `json:"field_name"`

	// Limit 分布桶数上限；≤0 或 >50 后端归一为 20。
	Limit    *int    `json:"limit,omitempty"`
	QuerySql *string `json:"query_sql,omitempty"`

	// QueryType 数据源解析规则与 preview 一致。
	QueryType *string `json:"query_type,omitempty"`
	TableName *string `json:"table_name,omitempty"`
}

// FieldDistributionResponse POST /api/datasources/{id}/field-distribution 响应。
type FieldDistributionResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 字段值分布（entity.FieldDistribution）；distribution 恒为数组。
	Data FieldDistribution `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// FieldGroup 维度/指标字段组。
type FieldGroup struct {
	// Alias omitempty：空值不会出现在请求 JSON 中。
	Alias  *string  `json:"alias,omitempty"`
	Fields []string `json:"fields"`
	Id     string   `json:"id"`
}

// FieldValueCount 单个取值的计数与占比。
type FieldValueCount struct {
	Count int64 `json:"count"`

	// Percentage 百分比，保留两位小数（如 12.34）。
	Percentage float64     `json:"percentage"`
	Value      interface{} `json:"value"`
}

// Filter 过滤条件。
type Filter struct {
	Field string `json:"field"`
	Id    string `json:"id"`

	// Logic 与其他条件的连接逻辑（如 "and" / "or"）。
	Logic    string      `json:"logic"`
	Operator string      `json:"operator"`
	Value    interface{} `json:"value"`
	ValueEnd interface{} `json:"value_end,omitempty"`
}

// HealthData defines model for HealthData.
type HealthData struct {
	// Status Example: ok
	Status string `json:"status"`
}

// HealthResponse GET /health 响应：Envelope 特化 data 为 HealthData。
type HealthResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`
	Data HealthData   `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// OkData 删除/测试连接等无业务负载端点的成功负载。
type OkData struct {
	Status OkDataStatus `json:"status"`
}

// OkDataStatus defines model for OkData.Status.
type OkDataStatus string

// OkResponse Envelope 特化 data 为 OkData（{status: "ok"}）。
type OkResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 删除/测试连接等无业务负载端点的成功负载。
	Data OkData `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// PreviewResult 预览结果（entity.PreviewResult）；两字段经 response 归一化， 恒为数组（不会为 null）。
type PreviewResult struct {
	Columns []string  `json:"columns"`
	Data    []DataRow `json:"data"`
}

// QueryConfig POST /api/datasets/{id}/query 请求体（entity.QueryConfig）。 所有字段可缺省（后端绑定零值）。
type QueryConfig struct {
	DimensionGroups *[]FieldGroup `json:"dimension_groups,omitempty"`
	Filters         *[]Filter     `json:"filters,omitempty"`
	Limit           *int          `json:"limit,omitempty"`
	MetricGroups    *[]FieldGroup `json:"metric_groups,omitempty"`
	Sort            *SortConfig   `json:"sort,omitempty"`
}

// ResponseCode 业务状态码，与 backend/internal/response/response.go 常量一一对应。
type ResponseCode int

// Share 分享响应实体（entity.Share，backend/internal/domain/entity/share.go）。 password 为 json:"-" 永不外泄（bcrypt 哈希也不回显），has_password 是 唯一的密码保护信号。
type Share struct {
	ChartId int `json:"chart_id"`

	// CreatedAt RFC3339 时间；数据库时间戳无效时为空字符串。
	CreatedAt string `json:"created_at"`

	// ExpiresAt RFC3339 过期时间；指针字段，键恒在，无过期设置时为 null。
	ExpiresAt *string `json:"expires_at"`

	// HasPassword 是否设置了访问密码（替代外泄的 password 字段）。
	HasPassword bool `json:"has_password"`
	Id          int  `json:"id"`

	// Token 后端随机生成，格式 hex(8 字节)-hex(8 字节)，如 "3a7f...c2-9d1e...f0"。
	Token string `json:"token"`
}

// ShareCreateRequest POST /api/shares 请求体（handler 匿名 struct：chart_id/password/expires_at）。
type ShareCreateRequest struct {
	// ChartId 被分享的图表 ID；后端不校验其存在性。
	ChartId int `json:"chart_id"`

	// ExpiresAt RFC3339 过期时间；非 RFC3339 的字符串被后端解析失败后静默忽略 （等同不设置过期）。
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Password 访问密码；空串/缺省表示不设密码；非空以 bcrypt 哈希落库。
	Password *string `json:"password,omitempty"`
}

// ShareListResponse GET /api/shares 响应：data 为 Share 数组（id 倒序，无分页）。
type ShareListResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`
	Data []Share      `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// ShareResponse 分享 CRUD / verify 响应：data 为单个 Share。
type ShareResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 分享响应实体（entity.Share，backend/internal/domain/entity/share.go）。 password 为 json:"-" 永不外泄（bcrypt 哈希也不回显），has_password 是 唯一的密码保护信号。
	Data Share `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// ShareVerifyRequest POST /api/shares/{token}/verify 请求体。
type ShareVerifyRequest struct {
	// Password 待校验密码；无密码的分享恒通过。
	Password *string `json:"password,omitempty"`
}

// SortConfig defines model for SortConfig.
type SortConfig struct {
	Field string `json:"field"`

	// Order "asc" 或 "desc"。
	Order string `json:"order"`
}

// TableDataResponse GET /api/datasources/{id}/tables/{table}/data 响应。
type TableDataResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 分页表数据（entity.TableDataResult）；数组字段经归一化恒为数组， 无主键时 primary_keys 为空数组。
	Data TableDataResult `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// TableDataResult 分页表数据（entity.TableDataResult）；数组字段经归一化恒为数组， 无主键时 primary_keys 为空数组。
type TableDataResult struct {
	Columns     []string  `json:"columns"`
	Data        []DataRow `json:"data"`
	Page        int       `json:"page"`
	PageSize    int       `json:"page_size"`
	PrimaryKeys []string  `json:"primary_keys"`
	Total       int64     `json:"total"`
}

// TableInfo 表元数据（entity.TableInfo）。
type TableInfo struct {
	Comment string `json:"comment"`
	Name    string `json:"name"`
}

// TableListResponse GET /api/datasources/{id}/tables 响应：data 为 TableInfo 数组。
type TableListResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`
	Data []TableInfo  `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// TypeConfig 类型相关配置（entity.TypeConfig）。
type TypeConfig struct {
	Precision int `json:"precision"`
	Scale     int `json:"scale"`
}

// ChartId defines model for ChartId.
type ChartId = int

// DatasetId defines model for DatasetId.
type DatasetId = int

// DatasourceId defines model for DatasourceId.
type DatasourceId = int

// ShareToken defines model for ShareToken.
type ShareToken = string

// TableName defines model for TableName.
type TableName = string

// ListChartsParams defines parameters for ListCharts.
type ListChartsParams struct {
	// Limit 每页条数；缺省 100，≤0 或 >1000 后端回落为 100。
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset 偏移量；缺省 0，负数被后端归一化为 0。
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListDatasetsParams defines parameters for ListDatasets.
type ListDatasetsParams struct {
	// Limit 每页条数；缺省 100，≤0 或 >1000 后端回落为 100。
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset 偏移量；缺省 0，负数被后端归一化为 0。
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// UpdateDatasetColumnsJSONBody defines parameters for UpdateDatasetColumns.
type UpdateDatasetColumnsJSONBody = []DatasetColumn

// ListDatasourcesParams defines parameters for ListDatasources.
type ListDatasourcesParams struct {
	// Limit 每页条数。后端 getPaginationParams（handler/helpers.go）：缺省 100；
	// 值 ≤0 或 >1000 时回落为 100（实际硬上限是 1000）。
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset 偏移量；缺省 0，负数被后端归一化为 0。
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetTableDataParams defines parameters for GetTableData.
type GetTableDataParams struct {
	// Page 页码，从 1 开始；≤0 被后端归一为 1。
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 每页行数；≤0 归一为 20，上限 100（超出截断为 100）。
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// SortField 排序列；必须是该表的主键列，否则返回 Envelope.code = 50000（错误消息含 "sort field must be a primary key"）。
	SortField *string `form:"sort_field,omitempty" json:"sort_field,omitempty"`

	// SortOrder 排序方向，ASC/DESC（大小写不敏感）；缺省 ASC。
	SortOrder *string `form:"sort_order,omitempty" json:"sort_order,omitempty"`
}

// CreateChartJSONRequestBody defines body for CreateChart for application/json ContentType.
type CreateChartJSONRequestBody = ChartCreateRequest

// QueryChartJSONRequestBody defines body for QueryChart for application/json ContentType.
type QueryChartJSONRequestBody = ChartQueryRequest

// UpdateChartJSONRequestBody defines body for UpdateChart for application/json ContentType.
type UpdateChartJSONRequestBody = ChartUpdateRequest

// CreateDatasetJSONRequestBody defines body for CreateDataset for application/json ContentType.
type CreateDatasetJSONRequestBody = DatasetCreateRequest

// UpdateDatasetJSONRequestBody defines body for UpdateDataset for application/json ContentType.
type UpdateDatasetJSONRequestBody = DatasetUpdateRequest

// UpdateDatasetColumnsJSONRequestBody defines body for UpdateDatasetColumns for application/json ContentType.
type UpdateDatasetColumnsJSONRequestBody = UpdateDatasetColumnsJSONBody

// QueryDatasetJSONRequestBody defines body for QueryDataset for application/json ContentType.
type QueryDatasetJSONRequestBody = QueryConfig

// CreateDatasourceJSONRequestBody defines body for CreateDatasource for application/json ContentType.
type CreateDatasourceJSONRequestBody = DatasourceCreateRequest

// TestDatasourceConnectionJSONRequestBody defines body for TestDatasourceConnection for application/json ContentType.
type TestDatasourceConnectionJSONRequestBody = DatasourceTestConnectionRequest

// UpdateDatasourceJSONRequestBody defines body for UpdateDatasource for application/json ContentType.
type UpdateDatasourceJSONRequestBody = DatasourceUpdateRequest

// GetDatasourceFieldDistributionJSONRequestBody defines body for GetDatasourceFieldDistribution for application/json ContentType.
type GetDatasourceFieldDistributionJSONRequestBody = FieldDistributionRequest

// PreviewDatasourceJSONRequestBody defines body for PreviewDatasource for application/json ContentType.
type PreviewDatasourceJSONRequestBody = DatasourcePreviewRequest

// CreateShareJSONRequestBody defines body for CreateShare for application/json ContentType.
type CreateShareJSONRequestBody = ShareCreateRequest

// VerifySharePasswordJSONRequestBody defines body for VerifySharePassword for application/json ContentType.
type VerifySharePasswordJSONRequestBody = ShareVerifyRequest
