// Package idls provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package idls

// Defines values for ResponseCode.
const (
	CodeBadRequest    ResponseCode = 20100
	CodeBusinessError ResponseCode = 20400
	CodeInternalError ResponseCode = 50000
	CodeNotFound      ResponseCode = 20300
	CodeSuccess       ResponseCode = 20000
	CodeThirdPartyErr ResponseCode = 20500
	CodeUnauthorized  ResponseCode = 20200
)

// Valid indicates whether the value is a known member of the ResponseCode enum.
func (e ResponseCode) Valid() bool {
	switch e {
	case CodeBadRequest:
		return true
	case CodeBusinessError:
		return true
	case CodeInternalError:
		return true
	case CodeNotFound:
		return true
	case CodeSuccess:
		return true
	case CodeThirdPartyErr:
		return true
	case CodeUnauthorized:
		return true
	default:
		return false
	}
}

// Envelope 统一响应封装；HTTP 状态码恒为 200，业务状态由 code 表达。
type Envelope struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`

	// Data 业务数据；错误或无数据时为空对象 {}，不为 null
	Data interface{} `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// HealthData defines model for HealthData.
type HealthData struct {
	// Status Example: ok
	Status string `json:"status"`
}

// HealthResponse GET /health 响应：Envelope 特化 data 为 HealthData。
type HealthResponse struct {
	// Code 业务状态码，与 backend/internal/response/response.go 常量一一对应。
	Code ResponseCode `json:"code"`
	Data HealthData   `json:"data"`

	// Msg 提示消息；成功为 "success"，错误为可读错误描述
	Msg string `json:"msg"`

	// Trace 请求追踪 ID（X-Request-ID）
	Trace string `json:"trace"`
}

// ResponseCode 业务状态码，与 backend/internal/response/response.go 常量一一对应。
type ResponseCode int
